import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="dark">
      <body className={`${poppins.className} old-film-effect antialiased`}>
        {children}
        <div className="grain-effect" />
        <div className="scratch-lines" />
        <div className="scratch-lines scratch-2" />
        <div className="scratch-lines scratch-3" />
        <div className="flicker" />
        <div className="vignette" />
      </body>
    </html>
  );
}
