import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="dark">
      <body className={`${poppins.className} antialiased`}>
        {children}
        <div className="old-film-effect">
          <div className="grain-effect" />
          <div className="scratch-lines" />
          <div className="scratch-lines scratch-2" />
          <div className="scratch-lines scratch-3" />
          <div className="flicker" />
          <div className="vignette" />
        </div>
      </body>
    </html>
  );
}
